# Generated by Django 3.0.2 on 2020-03-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Žena'), ('M', 'Muž')], default=None, max_length=7)),
                ('age', models.CharField(choices=[('T', '15-20'), ('Y', '20-25'), ('A1', '25-35'), ('A2', '35-45'), ('A3', '45-55'), ('A4', '55-65'), ('S', '65+')], default=None, max_length=10)),
                ('education', models.CharField(choices=[('1', 'Základné'), ('2', 'Stredoškolské bez maturity'), ('3', 'Stredoškolské s maturitou'), ('4', 'Vysokoškolské'), ('0', 'Žiadne')], default=None, max_length=50)),
                ('student', models.BooleanField(default=False)),
                ('profession', models.CharField(choices=[('H', 'Zdravotníctvo'), ('E', 'Školstvo'), ('C', 'Stavbeníctvo'), ('R', 'Reštauračné služby'), ('B', 'Podnikanie')], default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_generator.Question')),
            ],
        ),
    ]
