# Generated by Django 3.0.2 on 2020-03-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline_size', models.IntegerField(choices=[(1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3')], default=None)),
                ('font_size', models.IntegerField(choices=[(1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3')], default=None)),
                ('font_style', models.IntegerField(choices=[(1, 'Style 1'), (2, 'Style 2'), (3, 'Style 3')], default=None)),
                ('image_count', models.IntegerField(choices=[(1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3')], default=None)),
                ('colors', models.IntegerField(choices=[(1, 'Group 1'), (2, 'Group 2'), (3, 'Group 3')], default=None)),
                ('text_length', models.IntegerField(choices=[(1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3')], default=None)),
                ('hyperlink_count', models.IntegerField(choices=[(1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3')], default=None)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_generator.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='PageRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credibility', models.IntegerField(choices=[(-3, 'Uncredible 3'), (-2, 'Uncredible 2'), (-1, 'Uncredible 1'), (0, 'Dont Know'), (1, 'Credible 1'), (2, 'Credible 2'), (3, 'Credible 3')], default=None)),
                ('headline_length', models.BooleanField(default=False)),
                ('headline_size', models.BooleanField(default=False)),
                ('font_size', models.BooleanField(default=False)),
                ('font_style', models.BooleanField(default=False)),
                ('image_count', models.BooleanField(default=False)),
                ('colors', models.BooleanField(default=False)),
                ('text_length', models.BooleanField(default=False)),
                ('hyperlink_count', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_generator.Page')),
            ],
        ),
    ]
