# Generated by Django 3.0.2 on 2020-03-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0002_page_pagerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerating',
            name='credibility',
            field=models.IntegerField(choices=[(-3, 'Úplne nedôveryhodná'), (-2, 'Dosť nedôveryhodná'), (-1, 'Trochu nedôveryhodná'), (0, 'Neviem posúdiť'), (1, 'Trochu dôveryhodná'), (2, 'Dosť dôveryhodná'), (3, 'Úplne dôveryhodná')], default=None),
        ),
    ]
