# Generated by Django 3.0.2 on 2020-03-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0006_auto_20200321_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
