# Generated by Django 3.0.2 on 2020-03-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0007_auto_20200321_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='session_id',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
