# Generated by Django 3.0.2 on 2020-03-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0008_participant_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='session_id',
            field=models.CharField(default='Abc', max_length=500),
        ),
    ]
