# Generated by Django 3.0.2 on 2020-03-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0009_auto_20200321_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='session_id',
            field=models.CharField(max_length=500),
        ),
    ]
