# Generated by Django 3.0.2 on 2020-03-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0010_auto_20200321_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
