# Generated by Django 3.1.4 on 2020-12-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0011_page_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerating',
            name='page_layout',
            field=models.BooleanField(default=False),
        ),
    ]
