# Generated by Django 3.1.4 on 2020-12-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0012_pagerating_page_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='colors',
            field=models.IntegerField(choices=[(1, 'Group 1'), (2, 'Group 2'), (3, 'Group 3'), (4, 'Group 4')], default=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='font_style',
            field=models.IntegerField(choices=[(1, 'Style 1'), (2, 'Style 2'), (3, 'Style 3'), (4, 'Style 4')], default=None),
        ),
    ]
